### ISSUE TITLE
when i started to run the docker file I got this at step 15.

### ISSUE THREAD

**Issue by Mohamedellebody** [salinaaaaaa/-deprecated-NVIDIA-GPU-Tensor-Core-Accelerator-PyTorch-OpenCV#3]
Step 15/64 : RUN apt-get update && apt-get install -y --no-install-recommends     libnvinfer7=7.1.3-1+cuda11.0     libnvinfer-dev=7.1.3-1+cuda11.0     libnvinfer-plugin7=7.1.3-1+cuda11.0     libnvinfer-plugin-dev=7.1.3-1+cuda11.0
 ---> Running in d3847754a230
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease [1581 B]
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [1082 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [3099 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1568 kB]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1311 kB]
Get:13 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [22.9 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [1352 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [30.0 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3524 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2342 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [20.5 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [64.0 kB]
Fetched 27.8 MB in 31s (908 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libnvinfer7
E: Version '7.1.3-1+cuda11.0' for 'libnvinfer-dev' was not found
E: Unable to locate package libnvinfer-plugin7
E: Version '7.1.3-1+cuda11.0' for 'libnvinfer-plugin-dev' was not found
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends     libnvinfer7=7.1.3-1+cuda11.0     libnvinfer-dev=7.1.3-1+cuda11.0     libnvinfer-plugin7=7.1.3-1+cuda11.0     libnvinfer-plugin-dev=7.1.3-1+cuda11.0' returned a non-zero code: 100

**Comment by daddydrac** [comment]
Its now fixed.

**Comment by daddydrac** [comment]
Closing.
